In [52]:
import pandas as pd

In [53]:
df=pd.read_csv("IMDB Dataset.csv")

In [54]:
df.shape

(50000, 2)

In [55]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [56]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [57]:
df.drop_duplicates(inplace=True)

In [58]:
df.shape

(49582, 2)

# pre-processing

1.Coverting to lowercase

In [59]:
df["review"]=df["review"].str.lower()

 2.Removing the URLs

In [60]:
import re

 #sample_text="abc is the word,abc"# abc=>xyz
# new_text=re.sub("abc","xyz",sample_text)

In [15]:
 # new_text

In [61]:
def remove_urls(text):
    re.sub(r"https\S+","",text) # (pattern,replication,string) e.g-https://www.google.com
    return text
df["review"]=df["review"].apply(remove_urls)

##### 3. Removing punctuations

In [62]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]","",text) # A-Z a-z 0-9\s
    return text

df["review"]=df["review"].apply(remove_punctuations)

In [63]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

##### 4.Removing HTML

In [64]:
def remove_html(text):
    text=re.sub("r<.*?>","",text)
    return text

df["review"]=df["review"].apply(remove_html)

In [65]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

##### 5.Removing the stopwords

In [66]:
import nltk  

nltk.download("punkt")
nltk.download("punk_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to C:\Users\HP/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Error loading punk_tab: Package 'punk_tab' not found in
[nltk_data]     index
[nltk_data] Downloading package stopwords to C:\Users\HP/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [67]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [40]:
#sample_text="I like coding in python !"
#tokens=word_tokenize(sample_text)

In [42]:
#tokens

In [68]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text=text.replace(word,"")

    return text

df["review"]=df["review"].apply(remove_stopwords)

In [69]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

##### 6. Stemming

In [70]:
# running=> run
# played=> play
# porterStemming

from nltk.stem import PorterStemmer

In [72]:
def stemming(text):
    ps=PorterStemmer()
    stemmed_words=[]

    tokens=word_tokenize(text)
    for token in tokens:
        stemmed_token=ps.stem(token)
        stemmed_words.append(stemmed_token)

    return" ".join(stemmed_words)

df["review"]=df["review"].apply(stemming)

In [73]:
df.head()

                                              review sentiment
0  e revew nte wtchg 1 oz epo hook rght exctl hpp...  positive
1  wder ltle prducti br br film techniqu unssum l...  positive
2  hugh h wer w pen me h ummer weeken ng n r cne ...  positive
3  bci fli e boy jke hk zobe cloe pn fghg ebr br ...  negative
4  peer me love i vu unng film wch mr mei fer u v...  positive

#### 7.Encoding

In [74]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["sentiment"]=le.fit_transform(df["sentiment"])

In [75]:
y=df["sentiment"]

In [76]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(max_features=5000)
X=tf.fit_transform(df["review"])

In [78]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3316103 stored elements and shape (49582, 5000)>

In [79]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3316103 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3962)	0.07314282300609996
  (0, 4935)	0.14950938847188663
  (0, 3426)	0.4698640965354833
  (0, 1491)	0.16244209325938672
  (0, 2283)	0.07923919927127605
  (0, 3978)	0.15178703358489806
  (0, 1629)	0.09605370040119345
  (0, 2328)	0.059413310971479213
  (0, 264)	0.08228624418462524
  (0, 1935)	0.16942996486293824
  (0, 4314)	0.05899315405421301
  (0, 4166)	0.05729696611296147
  (0, 4709)	0.2770729449171833
  (0, 4201)	0.08362913949999684
  (0, 2065)	0.03483596838994734
  (0, 4215)	0.2641922463354714
  (0, 1940)	0.07943834322627065
  (0, 2199)	0.0901262901744208
  (0, 3802)	0.043113833333287284
  (0, 3816)	0.08133575442157247
  (0, 3924)	0.09368624090115052
  (0, 4125)	0.07568854099337527
  (0, 4204)	0.08005374587498516
  (0, 614)	0.0977245052147425
  (0, 4605)	0.06771933259930923
  :	:
  (49581, 3013)	0.6322832966347672
  (49581, 3600)	0.07708762613869068
  (49581, 256)	0.08283729185906373
  (49581, 4123)	0.09153434378227822
  (49581, 427)	0.06226178108370525
  (49581, 515)	0.10642698607162616
  (49581, 4632)	0.08094985102172797
  (49581, 2616)	0.13341204943087576
  (49581, 1505)	0.1205769318065429
  (49581, 2311)	0.10627919032226671
  (49581, 2656)	0.08997373475343341
  (49581, 4541)	0.12696239513563262
  (49581, 367)	0.1321628987820879
  (49581, 4880)	0.2404904575119017
  (49581, 4703)	0.13086508465005006
  (49581, 621)	0.1297007062963437
  (49581, 4742)	0.10285633187856055
  (49581, 1492)	0.12072046070109305
  (49581, 3948)	0.17366105732823034
  (49581, 2603)	0.17858909593995048
  (49581, 2343)	0.14429517003247952
  (49581, 523)	0.1262025996828523
  (49581, 4973)	0.15568356974471215
  (49581, 2087)	0.1760027848307958
  (49581, 3624)	0.1715216241299442

### Dataset & Data Loaders

In [80]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [84]:
X_train.shape

(39665, 5000)

In [85]:
X_test.shape

(9917, 5000)

In [93]:
import torch
from torch.utils.data import TensorDataset,DataLoader

In [95]:
X_train = X_train  # already a numpy array, no conversion needed
X_test = X_test

In [96]:
X_train

array([[0.20419695, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(39665, 5000))

In [98]:
train_set=TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()

)

test_set=TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
    
)

In [99]:
train_loader=DataLoader(train_set,shuffle=True,batch_size=64)
test_loader=DataLoader(test_set,shuffle=True,batch_size=64)

### Build our RNN

In [103]:
import torch.nn as nn
import torch.optim as optim

In [104]:
class RNN(nn.Module):
 def __init__(self,input_size,hidden_size=128,num_layers=1):
    super().__init__()

    self.hidden_size=hidden_size
    self.num_layers=num_layers

    #RNN  layer

    self.rnn=nn.RNN(input_size,hidden_size,num_layers,batch_first=True)

    # fully connected layer

    self.fc=nn.Linear(hidden_size,1)
     
 def forward(self,X):
     #optional=> shape(num of layers,batch size,hidden size)

    h0=torch.zeros(self.num_layers,X.size(0),self.hidden_size)

    out,_=self.rnn(X,h0)

    #1st value=>hidden state of all the timestamp=>(batch,seq_len,hidden size)
    #2nd value= final hidden state of last timestamp

    out=self.fc(out[:,-1,:])

    return out

In [105]:
input_size=X_train.shape[1]

model=RNN(input_size)

criterion=nn.BCELoss()
optimizer=optim.Adam(model.parameters())

### Training the RNN_Model

In [110]:
epochs=10

for epoch in range(epochs):
    model.train()

    for Xb,yb in train_loader:
        optimizer.zero_grad()

        Xb=Xb.unsqueeze(1)# add singleton direction

        outputs=model(Xb)# (batch_size=1)

        outputs=torch.sigmoid(outputs.squeeze())#(batch_size,)=>probability
        loss=criterion(outputs,yb)# compute loss
        loss.backward() # backward
        optimizer.step() # weights update

    print(f"epoch={epoch+1}/{epochs} and loss={loss.item()}")

epoch=1/10 and loss=0.42235007882118225
epoch=2/10 and loss=0.23856499791145325
epoch=3/10 and loss=0.26891642808914185
epoch=4/10 and loss=0.4340987801551819
epoch=5/10 and loss=0.317935049533844
epoch=6/10 and loss=0.33176061511039734
epoch=7/10 and loss=0.3388744592666626
epoch=8/10 and loss=0.2850908637046814
epoch=9/10 and loss=0.24356035888195038
epoch=10/10 and loss=0.25818896293640137

### Evaluate

In [ ]:
model.eval()

with torch.no_grad():
    correct_vals=0
    tot_vals=0

    for Xb,yb in test_loader:
        Xb=Xb.unsqueeze(1)

        outputs=model(Xb)
        predicted=(torch.sigmoid(outputs.squeeze())>0.5).float()

        tot_vals+=yb.size(0)
        correct_vals+=(predicted==yb).sum().item()

    print(f"accuracy={correct_vals/tot_vals*100}")